// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACZLwyjT2ToLMnZRjl7Qd6eu4M43OI_Os',
    appId: '1:782082505519:web:eeaad740fdf52e19227fda',
    messagingSenderId: '782082505519',
    projectId: 'newsapp-8d42b',
    authDomain: 'newsapp-8d42b.firebaseapp.com',
    storageBucket: 'newsapp-8d42b.appspot.com',
    measurementId: 'G-GKTQRRZNJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwufs06Ta4PMqDL9xLmorfLXOOsE223DQ',
    appId: '1:782082505519:android:794c8cd7204a0b59227fda',
    messagingSenderId: '782082505519',
    projectId: 'newsapp-8d42b',
    storageBucket: 'newsapp-8d42b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNFUWDww_7bp-eSd7QSL0IC_X3eG_ymaA',
    appId: '1:782082505519:ios:659e90593faeeddb227fda',
    messagingSenderId: '782082505519',
    projectId: 'newsapp-8d42b',
    storageBucket: 'newsapp-8d42b.appspot.com',
    iosBundleId: 'com.andri.newsappBionic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNFUWDww_7bp-eSd7QSL0IC_X3eG_ymaA',
    appId: '1:782082505519:ios:16396b5ab96c3466227fda',
    messagingSenderId: '782082505519',
    projectId: 'newsapp-8d42b',
    storageBucket: 'newsapp-8d42b.appspot.com',
    iosBundleId: 'com.example.newsappBionic.RunnerTests',
  );
}
